[package]
name = "gpt"
version = "0.1.0"
edition = "2021"

[dependencies]
chatgpt_rs = "1.2.3"
clap = { version = "4.4.3", features = ["derive", "env"] }
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }
