[package]
name = "gpt"
version = "0.1.0"
edition = "2021"

[dependencies]
chatgpt_rs = { version = "1.2.3", features = ["streams"] }
clap = { version = "4.4.3", features = ["derive", "env"] }
futures-util = "0.3.28"
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }
